### ISSUE TITLE
Loki Canary hit max concurrent tail request limit #2894

### ISSUE THREAD

**Issue by AClarkie** [unguiculus/loki-helm-chart#33]
Hello,

I've raised the following bug in the main loki github:
https://github.com/grafana/loki/issues/2894

I'm just wondering if you've hit this issue at all in your testing, my config is below:

```
# nameOverride -- Overrides the chart's name
nameOverride: ""

serviceAccount:
  # serviceAccount.create -- Specifies whether a ServiceAccount should be created
  create: true

# ServiceMonitor configuration
serviceMonitor:
  # serviceMonitor.enabled -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: true

tolerations:
  - effect: NoSchedule
    operator: Exists

# extraArgs -- Additional CLI args for the canary
extraArgs:
  - -labelname=pod
  - -labelvalue=$(POD_NAME)

# lokiAddress -- The Loki server URL:Port, e.g. loki:3100
lokiAddress: loki-gateway:80
```
